// <auto-generated />
using BasketballTeamsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BasketballTeamsApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210219191659_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BasketballTeamsApi.Core.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageAssist")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("AveragePoints")
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("AverageRebound")
                        .HasColumnType("decimal(4,1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 32,
                            AverageAssist = 9.1m,
                            AveragePoints = 32.1m,
                            AverageRebound = 4.9m,
                            IsDeleted = false,
                            JerseyNumber = 30,
                            Name = "Stephen Curry",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 31,
                            AverageAssist = 7.4m,
                            AveragePoints = 27.3m,
                            AverageRebound = 6.5m,
                            IsDeleted = false,
                            JerseyNumber = 11,
                            Name = "Klay Thompson",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 30,
                            AverageAssist = 4.2m,
                            AveragePoints = 14.5m,
                            AverageRebound = 8.7m,
                            IsDeleted = false,
                            JerseyNumber = 23,
                            Name = "Draymond Green",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 30,
                            AverageAssist = 6.1m,
                            AveragePoints = 30.1m,
                            AverageRebound = 3.9m,
                            IsDeleted = false,
                            JerseyNumber = 0,
                            Name = "Damian Lillard",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            Age = 36,
                            AverageAssist = 7.1m,
                            AveragePoints = 21.8m,
                            AverageRebound = 6.6m,
                            IsDeleted = false,
                            JerseyNumber = 0,
                            Name = "Carmelo Anthony",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            Age = 29,
                            AverageAssist = 11.4m,
                            AveragePoints = 26.1m,
                            AverageRebound = 5.2m,
                            IsDeleted = false,
                            JerseyNumber = 3,
                            Name = "C. J. McCollum",
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("BasketballTeamsApi.Core.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            CourtName = "Case Center",
                            IsDeleted = false,
                            Name = "Golden State Warriors"
                        },
                        new
                        {
                            Id = 2,
                            Country = "USA",
                            CourtName = "Moda Center at the Rose Quarter",
                            IsDeleted = false,
                            Name = "Portland Trail Blazers"
                        });
                });

            modelBuilder.Entity("BasketballTeamsApi.Core.Entities.Player", b =>
                {
                    b.HasOne("BasketballTeamsApi.Core.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("BasketballTeamsApi.Core.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
